### ISSUE TITLE
Make modal responsive ... Nothing huge needed

### ISSUE THREAD

**Issue by IamManchanda** [dai-siki/vue-image-crop-upload#70]
With Sass version, 
I did in my projects like this 

```scss
.vue-image-crop-upload {
  .vicp-wrap {
    @include breakpoint(small only) {
      width: 100%;
      height: 100vH;
    }
  }
}
```
